### ISSUE TITLE
Module naming

### ISSUE THREAD

**Issue by pbchase** [ctsit/prevent_past_or_future_dates#2]
I am starting a discussion about the name of this module.  At the moment, that name is `past_future_date_tags`.  Other proposals are:

* prevent past or future dates
* past and future date tags
* dynamic date limiter
* constrain dates
* date constraint
* dynamic date tags

I welcome other suggestions

**Comment by mbentz-uf** [comment]
My vote is for `prevent past or future dates`.

**Comment by pbchase** [comment]
Taryn and I made the executive decision.  We will call the module "Prevent Past or Future Dates". To implement this change, we need to make these changes:

1. Rename the repo `prevent_past_or_future_dates`.
2. Edit the README to use the name _Prevent Past or Future Dates_ instead of the old name. This change needs to be reflected in multiple places.
3. Change the name space to _PreventPastOrFutureDates_ in `config.json` and `ExternalModule.php`
4. Change the name to _Prevent Past or Future Dates_ in `config.json`
5. Change the name to _Prevent Past or Future Dates_ in the JS files.
6. Add the new name in the AUTHORS files

Deploy the newly renamed module to stage_b for Taryn to review

**Comment by pbchase** [comment]
Addressed by PR #3
